---
title: A collection of climate/weather data for the US and the world
author: admin
date: '2021-07-03'
slug: a-collection-of-climate-weather-data-for-the-us-and-the-world
categories:
  - Data
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2021-07-03T15:07:40-05:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []


output:
  blogdown::html_page:
    toc: true
    toc_depth: 3


---

This post is to collect the climate/weather data I have seen in the literature for the United States and probably the world. This collection differs from the data sources that are well known by scholars, such as data from NOAA (mostly observations from ground stations). Instead, it covers gridded data that are climate model output. I will also attach the associated paper that uses the data. 


# GRIDMET: University of Idaho Gridded Surface Meteorological Dataset

This dataset provides high spatial resolution (roughly 4km) daily surface fields of temperature, precipitation, wind, humidity and radiation across the contiguous United States from 1979 to present. The dataset blends the [PRISM](https://prism.oregonstate.edu/) with the high temporal resolution data from the National Land Data Assimilation System ([NLDAS](https://ldas.gsfc.nasa.gov/)). See the [website](https://developers.google.com/earth-engine/datasets/catalog/IDAHO_EPSCOR_GRIDMET#description) for more details.

This dataset is an ideal source for "secondary" weather data, including wind speed, humidity (relative and specific), and radiation. While temperature and precipitation are the most widely used data in the climate change assessment literature, those secondary variables could be critical in certain cases. 

- Coverage: The Contiguous United States
- Temporal resolution: Daily
- Spatial resolution: 4km * 4km
- Variables: Precipitation, maximum relative humidity, minimum relative humidity, specific humidity, surface downward shortwave radiation, wind direction, minimum temperature, maximum temperature. wind velocity at 10m, etc. See the full list from [here](https://developers.google.com/earth-engine/datasets/catalog/IDAHO_EPSCOR_GRIDMET#bands)


Related reference

- David B. Lobell and Jennifer A. Burney, 2021. Cleanter air has contributed one-fifth of US maize and soybean yield gains since 1999. Environmental Research Letters. [Link](https://iopscience.iop.org/article/10.1088/1748-9326/ac0fa4/pdf).




