# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: "Working papers"
    url: '#workingpaper'
    weight: 21
  - name: "Publications"
    url: '#publication'
    weight: 20
  - name: "Teaching"
    url: '#teaching'
    weight: 30
  - name: "Useful Data"
    url: '#data'
    weight: 31
  - name: "Notes in R"
    url: '#notes_in_r'
    weight: 32
  - name: "Regular Posts"
    url: '#regular_post'
    weight: 33

  - name: "Gallery"
    url: '#gallery'
    weight: 45

  - name: "Contact"
    url: '#contact'
    weight: 50


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
