---
title: Mirco-level data in China
author: Yabin Da
date: '2020-09-26'
slug: MircoChina
categories:
  - Data
tags:
  - Mirco data
  - China
subtitle: ''
authors: [Yabin Da]
lastmod: '2022-06-15T23:24:16-05:00'
featured: no
draft: false
math: true
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
output:
  blogdown::html_page:
    toc: true
    toc_depth: 4
---

# Introduction

This section is designated to summerize commonly used mirco data for China. Most of the data were collected through surveys conducted by government and universities. I will update this document when I find new data sources in the literature. I will also attach papers that adpoted these data set.

Note that Chinese National Survey Data Arhive provides plenty of mrico-data. Most of the dataset below can be accessed there. See the [website](http://cnsda.ruc.edu.cn/index.php) for details.

The Open Research Data Platform of Peking University holds the China Survey Data Archive, from which you might find some data that are not commonly used. See the [website](https://opendata.pku.edu.cn/dataverse/CSDA) for details.


## China Health and Nutrition Survey (CHNS)


- Year of survey

  1989, 1991, 1993, 1997, 2000, 2004, 2006, 2009, 2015, and ongoing

- Summary of data

  The survey was designed to test the health effects of nutrition and family planning policies, and study how the role of China's social and economic changes in the health and nutritional status of the population as a whole. Survey covering households, nutrition, health, adults, children, and communities.

- Unit of analysis

  Individual, households, communities

- Data access

  The website is: <http://www.cpc.unc.edu/projects/china>

- Availiability

  Publicly available

- Relate applied papers

  - Chengzheng Li and Zheng Pan (2020). How do extremely high temperatures affect labor market performance? Evidence from rural China. _Empirical Economcis_. [Link](https://link.springer.com/article/10.1007/s00181-020-01954-9#:~:text=The%20female%20labor%20force%20in,consequences%20of%20unfavorable%20temperature%20shocks.)



## **Chinese Longitudinal Healthy Longevity Survey (CLHLS)**

- Year of survey

  1998, 2000, 2002, 2005 (not sure whether it's ongoing or not)

- Summary of data

  The objectives of this project was to study the impact of human health and longevity of the social, behavioral, environmental and biological factors, to fill the gaps of scientific research on aging and health information based on health policy.

- Unit of analysis

  Individual

- Data access

  The website is: <http://w3.pku.edu.cn/academic/ageing/index.html>
  The website appears not working.

- Availiability

  Need to download, sign, and fax the DATA USE AGREEMENT to Dr. Liu.




## Chinese General Social Survey (CGSS)

- Year of survey

  2003 to 2018, except for 2004.

- Summary of data

  The CGSS is aimed to systematically monitor the changing relationship between social structure and quality of life in both urban and rural China. Social structure refers to dimensions of social group and organization as well as networks of social relationships. Quality of life is the objective and subjective aspects of the people well-being both at the individual and aggregate levels. The CGSS aims to collect quantitative data about (1) measures of social structure, its stability and change, (2) measures of quality of life, objective and subjective, and (3) measures of underlying mechanisms linking social structure and quality of life.
  In the newest available 2017 survey, we can find data on the usage of internet for individual and household.

- Unit of analysis

  Individual and household

- Data access

  The website is: <http://cgss.ruc.edu.cn/index.php?r=index/index>


- Availiability

  Need registeration.



## Urban Household Survey (UHS)

- Year of survey

  From 1986 to 1992; from 1993 to 1997

- Summary of data

  The Urban Household Survey aims to study the conditions and standard of living of urban households. With the use of sampling techniques and daily accounting method, the survey collects data from non-agricultural households in different cities and counties. It records household information about income and consumption expenditure, demographic characteristics, work and employment, accommodation and other family related matters. This is a continuous, large scale social-economic survey, which can be traced back to 1955. The survey became regularized and professionalized since 1984. The USC collections start with 1986.

- Unit of analysis

  Individual, household

- Data access

  The website is: <http://ww2.usc.cuhk.edu.hk/DCS/Catalog.aspx>


- Availiability

  Need to purchase from the University of Hong Kong

- Additional note

  The Rural Household Survey should also exist, yet I did not find.


## **Chinese Family Panel Studies (CFPS)**

- Year of survey

  2010-2020 (beta) ongoing

- Summary of data

  China Family Panel Studies (CFPS) is a nationally representative, annual longitudinal survey of Chinese communities, families, and individuals launched in 2010 by the Institute of Social Science Survey (ISSS) of Peking University, China. The CFPS is designed to collect individual-, family-, and community-level longitudinal data in contemporary China. The studies focus on the economic, as well as the non-economic, wellbeing of the Chinese population, with a wealth of information covering such topics as economic activities, education outcomes, family dynamics and relationships, migration, and health. The CFPS is funded by the Chinese government through Peking University. The CFPS promises to provide to the academic community the most comprehensive and highest-quality survey data on contemporary China. Three key features of the CFPS are worth noting here.

- Unit of analysis

  Individual, household

- Data access

  The website is: <http://www.isss.pku.edu.cn/cfps/en/index.htm>
  Another website: <https://opendata.pku.edu.cn/dataset.xhtml?persistentId=doi:10.18170/DVN/45LCSO>

- Related papers
  - Yang et al., 2021. Does income inequality aggravate the impacts of air pollution on physical health? Evidence from China. _Environment, Development and Sustainability_. [Link](https://link.springer.com/article/10.1007/s10668-021-01522-w).
  - Zheng et al., 2022. When left-behind children become adults and parents: The long-term human capital consequences of parental absence in China. _China Economic Review_. [Link](https://doi.org/10.1016/j.chieco.2022.101821).
  - Huang Wei and Liu Hong, 2022. Early childhood exposure to health insurance and adolescent outcomes: Evidence from rural China. _Journal of Development Economics_. [Link](https://www.sciencedirect.com/science/article/pii/S0304387822000815#fn1)


- Availiability

  Registeration form


## **China Health and Retirement Longitudinal Study (CHARLS)**

- Year of survey

  Starting from 2011 and conducted every two years, ongoing

- Summary of data

  The China Health and Retirement Longitudinal Study (CHARLS) aims to collect a high quality nationally representative sample of Chinese residents ages 45 and older to serve the needs of scientific research on the elderly. The baseline national wave of CHARLS is being fielded in 2011 and includes about 10,000 households and 17,500 individuals in 150 counties/districts and 450 villages/resident committees. The individuals will be followed up every two years. All data will be made public one year after the end of data collection.

- Unit of analysis

  Individual, household

- Data access

  The website is: <http://charls.pku.edu.cn/pages/data/111/en.html>


- Availiability

  Registeration required


## China Longitudinal Aging Social Survey (CLASS)

- Year of survey

  2011 and 2012 (in trail), 2014 (baseline survey), 2016 and 2018 (following up survey)

- Summary of data

  CLASS is a large-scale nationwide social survey project directed by NSRC. By collecting social and economic data of the Chinese aging population regularly and systematically on both individual and community level, CLASS aims at understanding various problems and challenges that Chinese people would face during the aging process, and evaluating the real effects which various social security policies have achieved in improving the life-qualities of the older population. Survey trails were conducted for 2011 and 2012. The baseline survey was conducted in 2014. The following suvery was schedualed for 2016 and 2018.

- Unit of analysis

  Individual, household

- Data access

  The website is: <http://class.ruc.edu.cn/index.php?r=Index/index>
  Access through: <http://cnsda.ruc.edu.cn/>
  As of Oct 2, 2020, only the 2011 and 2012 data are available.

- Availiability

  Registeration required


## The China Urban Labor Survey (CULS)

- Year of survey

  2001, 2005 and 2010

- Summary of data

  The CULS was administered in five large Chinese cities: Shanghai, Shenyang, Wuhan, Xian and Fuzhou. The survey was administered by the Institute for Population Studies at the Chinese Academy of Social Sciences (CASS-IPS), in collaboration with local offices of the National Statistical Bureau in each of the five cities. In four of the cities the surveys were conducted by the urban survey unit of the provincial statistical bureau (the cheng diao dui) and in Shenyang by the enterprise survey unit.

- Unit of analysis

  Individual, household, community, and China urban adult cognitive ability

- Data access

  The website is: <https://opendata.pku.edu.cn/dataset.xhtml?persistentId=doi:10.18170/DVN/XMFDUI>
  Note that only the data in 2001 is available through the website above.
  Data in 2005 and 2010 should be available at Chinese Academy of Social Science (CASS), according to this [report](https://www.imf.org/external/pubs/ft/wp/2015/wp15151.pdf).


- Availiability

  Registeration required



## The Chinese Social Survey (CSS)

- Year of survey

  2006, 2008, 2011, 2013, 2015, 2017, and on goin

- Summary of data

  The Chinese Social Survey was initiated by the Institute of Sociology of the Chinese Academy of Social Sciences in 2005. The survey covers 31 provinces, including 151 districts/counties, 604 villages. Each wave of survey covers 7000 to 10000 households. Information on labor empolyment, household structure, household income, social ties, social insurances, etc can be found in the data set.

- Unit of analysis

  Individual, household

- Data access (in Chinese)

  The website is: <http://css.cssn.cn/css_sy/xmjs/xmgk/>

- Availiability

  Application is needed.



## **Rural-Urban Migration in China**

- Year of survey

  Probably started from 2008 or 2009. Currently data for 2016-2018 is publicly available.

- Summary of data

  RUMiC is a longitudinal survey conducted every year, collecting data about migrants’ health, education, employment, social networks, household income and expenditure, housing conditions, and place of origin. The annual sample size consists of 5,000 migrant households living in 15 cities across 9 major provinces with the highest level of rural to urban migration.

  In 2017, SDC successfully implemented the 10th wave of RUMiC. In this wave, a Computer-Assisted Personal Interviewing (CAPI) system replaced the traditional paper-and-pencil method and significantly improved data quality. In 2018 and 2019, all households participating in the 2016 or 2017 waves were interviewed by phone using the Computer-Assisted Telephone Interviewing (CATI) system, successfully tracing about 3,000 and nearly 2,500 households, respectively.

- Unit of analysis

  Individual, household

- Data access

  The website is: <https://sdc-iesr.jnu.edu.cn/sy_15947/main.htm>

- Availiability

  Application form is needed. The applicant is required to provide a research proposal.

  See the website above for detailed information.


## **China Education Panel Survey**

- Year of survey

  Currently 2013-2014, ongoing, will last for over 30 years

- Summary of data

  The China Education Panel Survey (CEPS) is a large-scale, nationally representative, longitudinal survey starting with two cohorts – the 7th and 9th graders in the 2013-2014 academic year. Documenting educational processes and transitions by which students progress through various educational stages, the CEPS aims at explaining the linkages between individuals' educational outcomes and multiple contexts of families, school processes, communities and social structure, and further studying the effects of educational outcomes during people's life course.

  The CEPS applies a stratified, multistage sampling design with probability proportional to size (PPS), randomly selecting a school-based, nationally representative sample of approximately 20,000 students in 438 classrooms of 112 schools in 28 county-level units in mainland China. The baseline survey of CEPS was completed in the 2013-2014 academic year, conducted by National Survey Research Center (NSRC) at Renmin University of China. The data are currently available for academic research. Follow-up surveys are annual as the sample adolescents matriculate throughout the junior-high stage and in the 1st, 3rd, 7th, 8th, 17th and 27th year after they graduate from junior-high. CEPS will last more than 30 years, during which a new cohort of 7th graders will be started in a 10-year interval.

  The student questionnaire includes topics such as students’ demographic characteristics, mobility and migration status, childhood experience, health status, household structure, parent-child interactions, in-school performance, extra curricular activities, relationship with teachers and peers, social behavior development, and expectations for the future.

  Parent questionnaire consists of questions about parents' demographic characteristics and lifestyles, parent-child interactions, educational environment and investment for child, community environment, parent-teacher interactions, and parents' perceptions of school education and expectations for the future of the child.

  Information on homeroom, teach characteristics, school administrators are also provided.

- Unit of analysis

  Individual, household

- Data access

  The website is: <https://sdc-iesr.jnu.edu.cn/sy_15947/main.htm>
  The website for downloading is: <http://cnsda.ruc.edu.cn/index.php?r=projects/view&id=72810330>

- Availiability

  Registeration is needed.



## **Chinese Household Income Project**

- Year of survey

  1989, 1996, 2003, 2008, and 2013 covering income and expenditure information in 1988, 1995, 2002, 2007, and 2013, respectively.

- Summary of data

  To track the dynamics of income distribution in China, the Chinese Household Income Project (CHIP) has conducted five waves of household surveys, in 1989, 1996, 2003, 2008 and 2013. They covered the income and expenditure information in 1988, 1995, 2002, 2007 and 2013 respectively and called CHIP1988, CHIP1995, CHIP2002, CHIP2007, and CHIP2013.

  All the CHIP waves contain surveys of urban and rural households. In view of the increased importance of rural-to-urban migration, and because the urban and rural household subsamples do not adequately cover migrants, the 2002 survey added a survey of rural-to-urban migrants. Thus, the 2002 CHIP survey includes three subsamples. The same procedure was adopted for the 2007 survey, which is also composed of three parts: the urban household survey, the rural household survey, and the rural-to-urban migrant household survey. This structure reflects China’s urban-rural division and the increased number of rural individuals who have migrated into the urban areas, especially during the last two decades.

  **Note that this data set includes data on rural-to-urban migration for year 2002, 2008, and 2009. The migration data should be consistent with the _Rural-Urban Migration in China_ which is also introduced in this collection. **


- Unit of analysis

  Individual, household

- Data access

  The website is: <http://www.ciidbnu.org/chip/index.asp?lang=EN>
  The website for downloading is: <http://www.ciidbnu.org/chip/index.asp?lang=EN>

- Availiability

  Registeration is needed. See this [website](http://www.ciidbnu.org/chip/about.asp?lang=EN) for details.




## **Chinese Household Income Project**

- Year of survey

  1989, 1996, 2003, 2008, and 2013 covering income and expenditure information in 1988, 1995, 2002, 2007, and 2013, respectively.

- Summary of data

  To track the dynamics of income distribution in China, the Chinese Household Income Project (CHIP) has conducted five waves of household surveys, in 1989, 1996, 2003, 2008 and 2013. They covered the income and expenditure information in 1988, 1995, 2002, 2007 and 2013 respectively and called CHIP1988, CHIP1995, CHIP2002, CHIP2007, and CHIP2013.

  All the CHIP waves contain surveys of urban and rural households. In view of the increased importance of rural-to-urban migration, and because the urban and rural household subsamples do not adequately cover migrants, the 2002 survey added a survey of rural-to-urban migrants. Thus, the 2002 CHIP survey includes three subsamples. The same procedure was adopted for the 2007 survey, which is also composed of three parts: the urban household survey, the rural household survey, and the rural-to-urban migrant household survey. This structure reflects China’s urban-rural division and the increased number of rural individuals who have migrated into the urban areas, especially during the last two decades.

  **Note that this data set includes data on rural-to-urban migration for year 2002, 2008, and 2009. The migration data should be consistent with the _Rural-Urban Migration in China_ which is also introduced in this collection. **


- Unit of analysis

  Individual, household

- Data access

  The website is: <http://www.ciidbnu.org/chip/index.asp?lang=EN>
  The website for downloading is: <http://www.ciidbnu.org/chip/index.asp?lang=EN>

- Availiability

  Registeration is needed. See this [website](http://www.ciidbnu.org/chip/about.asp?lang=EN) for details.

